"""A/B benchmark: heuristic decisions vs LLM curator decisions over a real corpus.

Three layers under test:

  A. lifecycle_decisions.should_expire / should_archive
  B. memory_engine._heuristic_decide_memory_action vs curator_consolidate
  C. graph._extract_entities_heuristic vs curator_extract_entities

Ground truth is hand-graded inline (NOT generated by an LLM — that would be
circular). For each case we compute:

  - agreement rate (heuristic vs LLM)
  - accuracy vs ground truth (per side)
  - false-positive / false-negative rates
  - latency (per layer)

Output: .memoirs/heuristic_vs_llm_quality.json + a printed table.

Usage
-----
    python scripts/quality_heuristic_vs_llm.py --smoke         # 10 cases per layer
    python scripts/quality_heuristic_vs_llm.py                 # default 30/layer
    python scripts/quality_heuristic_vs_llm.py --layer A       # one layer
    python scripts/quality_heuristic_vs_llm.py --no-llm        # heuristic only
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import statistics
import sys
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

log = logging.getLogger("quality_heuristic_vs_llm")


# ----------------------------------------------------------------------
# Hand-graded ground truth
# ----------------------------------------------------------------------

# Layer A.1 — EXPIRE: should the neighbor be expired given the candidate?
# Tuple: (cand_content, cand_type, neighbor_content, neighbor_type,
#         neighbor_age_days, neighbor_sim, GROUND_TRUTH)
EXPIRE_CASES: list[tuple[str, str, str, str, int, float, bool]] = [
    # Clearly should expire — same fact, replacing
    ("user lives in Paris", "fact", "user lives in Buenos Aires", "fact", 60, 0.92, True),
    ("user works at Anthropic", "fact", "user works at OpenAI", "fact", 90, 0.91, True),
    ("user uses macOS as primary OS", "fact", "user uses Ubuntu as primary OS", "fact", 45, 0.88, True),
    ("the database is now PostgreSQL", "decision", "we will use SQLite for the database", "decision", 50, 0.85, True),
    ("rename project to memoirs-v2", "decision", "project name is memoirs", "decision", 40, 0.83, True),
    ("user's phone is +34 600 111 222", "fact", "user's phone is +34 600 999 888", "fact", 40, 0.9, True),
    # Should NOT expire — similar surface but unrelated facts
    ("user uses Python at work", "fact", "user knows Python well", "fact", 60, 0.9, False),
    ("user prefers vim keybindings", "preference", "user prefers vim over emacs", "preference", 60, 0.9, False),
    # Should NOT expire — preference type (heuristic explicitly excludes)
    ("user prefers dark mode", "preference", "user prefers light mode", "preference", 60, 0.9, False),
    ("user prefers tabs", "style", "user prefers spaces", "style", 60, 0.9, False),
    # Should NOT expire — neighbor too young
    ("user lives in Madrid", "fact", "user lives in Lisbon", "fact", 10, 0.9, False),
    ("user works at Stripe", "fact", "user works at Square", "fact", 5, 0.92, False),
    # Should NOT expire — similarity too low
    ("user lives in Paris", "fact", "user mentioned visiting Paris once", "fact", 60, 0.55, False),
    ("the API uses GraphQL", "decision", "considered using REST", "decision", 60, 0.6, False),
    # Should NOT expire — type mismatch
    ("user lives in Tokyo", "fact", "moved to Tokyo last week", "task", 60, 0.85, False),
    # Genuine borderline — flagging True on heuristic; humans agree it expires
    ("the project root is now /srv/memoirs", "fact", "the project root is /opt/memoirs", "fact", 35, 0.82, True),
    ("user's editor is now Zed", "preference", "user's editor is VSCode", "preference", 60, 0.88, False),
    ("tests run with pytest -x", "decision", "tests run with pytest --tb=short", "decision", 50, 0.86, True),
    # Should NOT expire — empty / degenerate guarded above the heuristic
    # Two complementary facts (not contradictory)
    ("user has two cats", "fact", "user has a cat named Mira", "fact", 60, 0.84, False),
    ("user owns a laptop", "fact", "user owns a desktop", "fact", 60, 0.78, False),
    # More clear expirations
    ("the budget is now 50k", "decision", "budget allocated: 30k", "decision", 50, 0.86, True),
    ("user changed timezone to UTC+1", "fact", "user is in UTC-3", "fact", 60, 0.87, True),
    # Should NOT — refinement, not contradiction
    ("user uses Python 3.12", "fact", "user uses Python", "fact", 60, 0.87, False),
    # Should NOT — task age too low + decision text too different
    ("ship v1 by Friday", "task", "ship beta by next sprint", "task", 20, 0.7, False),
    # Clear expirations: 4 more
    ("user prefers Anthropic API", "fact", "user prefers OpenAI API", "fact", 60, 0.9, True),
    ("repo lives at github.com/foo/bar", "fact", "repo at gitlab.com/foo/bar", "fact", 40, 0.88, True),
    ("decided to use REST not GraphQL", "decision", "decided to use GraphQL", "decision", 50, 0.88, True),
    ("backup runs daily", "decision", "backup runs weekly", "decision", 45, 0.85, True),
    # Should NOT — same content essentially (would be UPDATE not EXPIRE)
    ("user lives in Buenos Aires", "fact", "user lives in Buenos Aires, Argentina", "fact", 60, 0.94, False),
    # Should NOT — tasks are time-bounded; an old task is not "expired by" a new one
    ("review PR #123", "task", "review PR #99", "task", 40, 0.78, False),
]

# Layer A.2 — ARCHIVE: stale + low-utility memoria.
# Tuple: (content, age_days, usage_count, score, type, GROUND_TRUTH)
ARCHIVE_CASES: list[tuple[str, int, int, float, str, bool]] = [
    # Clearly archive — old + never used
    ("ad-hoc tweak from 2024 dashboard layout work", 100, 0, 0.4, "task", True),
    ("scratch note from migration", 120, 0, 0.3, "task", True),
    ("temporary debug log from incident", 95, 0, 0.5, "fact", True),
    ("random observation about CSS bug", 110, 0, 0.4, "fact", True),
    ("notebook draft on RAG experiment", 100, 0, 0.6, "task", True),
    # Clearly archive — low score + somewhat old
    ("vague claim about user behavior", 70, 0, 0.15, "fact", True),
    ("thin observation, no detail", 65, 0, 0.1, "fact", True),
    ("very low-confidence guess", 80, 0, 0.18, "fact", True),
    # Should NOT archive — durable preference even if unused
    ("user prefers dark mode", 100, 0, 0.5, "preference", False),
    ("user prefers vim keybindings", 120, 0, 0.6, "preference", False),
    ("user prefers verbose error messages", 100, 0, 0.55, "style", False),
    # Should NOT archive — recently used
    ("user lives in Paris", 100, 5, 0.7, "fact", False),
    ("ship v2 launch plan", 100, 3, 0.7, "task", False),
    # Should NOT archive — too young
    ("recent decision on API shape", 30, 0, 0.5, "decision", False),
    ("new task to add caching", 20, 0, 0.4, "task", False),
    # Should NOT archive — high score
    ("user is allergic to peanuts", 200, 0, 0.9, "fact", False),
    ("decided we use Postgres for prod", 200, 0, 0.85, "decision", False),
    # Borderline → archive (low score, beyond 60d)
    ("dim memory of CSS hack", 65, 0, 0.19, "fact", True),
    # Borderline NOT — score exactly threshold
    ("note about CDN config", 70, 0, 0.21, "fact", False),
    # Should archive — old, unused, task
    ("write follow-up email after meeting (Q3 2024)", 200, 0, 0.5, "task", True),
    # Should NOT — high importance preference
    ("user is a vegetarian", 300, 0, 0.6, "preference", False),
    # Should archive — old quote with no usage
    ("temp credential rotation note", 150, 0, 0.3, "task", True),
    # Should NOT — used, even if old
    ("user prefers SI units", 200, 8, 0.7, "preference", False),
    # Should archive — clearly a stale TODO
    ("TODO: investigate flaky test in CI", 110, 0, 0.5, "task", True),
    # Should NOT — explicit decision, even if dusty
    ("decision: open-source under Apache-2.0", 250, 0, 0.7, "decision", False),
    # Should archive — old, unused, low score
    ("hint about Slack webhook", 100, 0, 0.18, "fact", True),
    # Should NOT — fresh
    ("project kickoff date is 2026-05-01", 5, 0, 0.6, "fact", False),
    # Should archive — low score for too long
    ("guess about caching layer", 80, 0, 0.12, "fact", True),
    # Should NOT — preference
    ("user likes minimal UI", 100, 0, 0.5, "preference", False),
    # Should archive — pure noise that lingered
    ("scratch debug thought", 95, 0, 0.4, "task", True),
]

# Layer B — consolidate: candidate + neighbors → action.
# Tuple: (cand_content, cand_type, neighbors=[(content, type, sim)],
#         GROUND_TRUTH_ACTION ∈ {ADD, UPDATE, MERGE, IGNORE, CONTRADICTION})
CONSOLIDATE_CASES: list[tuple[str, str, list[tuple[str, str, float]], str]] = [
    # Exact dup → UPDATE
    ("user prefers dark mode in editors", "preference",
     [("user prefers dark mode in editors", "preference", 1.0)], "UPDATE"),
    # Semantic dup, same type → MERGE
    ("user really enjoys writing Python code", "preference",
     [("user prefers Python for scripts", "preference", 0.91)], "MERGE"),
    # Semantic dup, different type → CONTRADICTION
    ("user prefers Python over Ruby", "preference",
     [("user uses Python at work daily", "fact", 0.92)], "CONTRADICTION"),
    # Brand new content, no neighbors → ADD
    ("user is in Buenos Aires this week for a conference", "fact", [], "ADD"),
    # Brand new content, weakly related neighbor → ADD
    ("user uses VSCode as primary editor", "fact",
     [("user prefers Python for scripting", "preference", 0.55)], "ADD"),
    # Conflicting fact → CONTRADICTION
    ("user lives in Paris these days", "fact",
     [("user lives in Buenos Aires currently", "fact", 0.92)], "CONTRADICTION"),
    # Empty content → IGNORE
    ("", "fact", [], "IGNORE"),
    # Whitespace only → IGNORE
    ("   ", "fact", [], "IGNORE"),
    # Same exact content, different types → MERGE (cross-type exact dup)
    ("user prefers Python over Ruby", "preference",
     [("user prefers Python over Ruby", "fact", 1.0)], "MERGE"),
    # Update a near-identical task
    ("ship v2 by Friday end of day", "task",
     [("ship v2 by friday end of day", "task", 0.99)], "UPDATE"),
    # Two similar prefs — MERGE
    ("user loves the rust-lang ecosystem", "preference",
     [("user prefers Rust for systems work", "preference", 0.9)], "MERGE"),
    # Mostly unrelated text — ADD
    ("setup reminder about coffee machine maintenance", "task",
     [("user prefers Python for scripts", "preference", 0.4)], "ADD"),
    # Clear contradiction in decisions
    ("we decided to use PostgreSQL for prod", "decision",
     [("we decided to use SQLite for prod", "decision", 0.88)], "CONTRADICTION"),
    # Same decision restated → MERGE
    ("use PostgreSQL for prod database", "decision",
     [("we decided to use Postgres for prod", "decision", 0.92)], "MERGE"),
    # Reinforcement of existing fact
    ("user has two cats named Mira and Pixel", "fact",
     [("user has two cats at home", "fact", 0.9)], "MERGE"),
    # New fact unrelated
    ("user changed primary editor to Helix", "fact",
     [("user prefers dark mode in editors", "preference", 0.3)], "ADD"),
    # Trivial / noise input — heuristic IGNOREs short noise
    ("ok", "fact", [], "IGNORE"),
    # Long elaboration of same preference
    ("user really really prefers vim mode in their editor for muscle memory reasons",
     "preference",
     [("user prefers vim keybindings", "preference", 0.85)], "MERGE"),
    # Cross-type exact content → MERGE
    ("user lives in NYC and works in Brooklyn", "preference",
     [("user lives in NYC and works in Brooklyn", "fact", 0.95)], "MERGE"),
    # Brand-new task
    ("draft Q3 OKRs for engineering team", "task", [], "ADD"),
    # Conflict tasks — different deadlines
    ("ship v2 by 2026-06-30 deadline", "task",
     [("ship v2 by 2026-05-15 deadline", "task", 0.86)], "CONTRADICTION"),
    # Same approach decision restated
    ("Auth flow uses OAuth2 with PKCE", "decision",
     [("auth flow: OAuth2 with PKCE", "decision", 0.9)], "MERGE"),
    # Add after weak similarity
    ("Project budget approved at 100k USD", "decision",
     [("project budget mentioned during sync", "fact", 0.5)], "ADD"),
    # Pure exact dup
    ("user is allergic to peanuts severely", "fact",
     [("user is allergic to peanuts severely", "fact", 1.0)], "UPDATE"),
    # Distinctive content but type swap
    ("user is allergic to peanuts severely", "preference",
     [("user is allergic to peanuts severely", "fact", 1.0)], "MERGE"),
    # New preference
    ("user wants email summaries every Monday", "preference",
     [("user prefers minimal notifications", "preference", 0.55)], "ADD"),
    # Task contradiction
    ("delete old DB backups older than 30d", "task",
     [("keep all DB backups indefinitely", "task", 0.83)], "CONTRADICTION"),
    # Task continuation
    ("continue refactor of auth module this week", "task",
     [("refactor auth module by next sprint", "task", 0.9)], "MERGE"),
    # Clean ADD
    ("user installed nvim plugin telescope today", "fact", [], "ADD"),
    # Weak overlap → ADD
    ("user mentioned a side project on rust embedded", "fact",
     [("user prefers Rust for systems work", "preference", 0.6)], "ADD"),
]

# Layer C — entity extraction.
# Tuple: (text, expected_entity_names_lowercased_set)
ENTITY_CASES: list[tuple[str, set[str]]] = [
    ("Memoirs uses SQLite and llama.cpp under Python.",
     {"memoirs", "sqlite", "llama.cpp", "python"}),
    ("We integrated Ollama with FastMCP for local inference.",
     {"ollama", "fastmcp"}),
    ("The project depends on `sentence-transformers` and Postgres.",
     {"sentence-transformers", "postgres"}),
    ("Migrating from Mem0 and Letta to Memoirs.",
     {"mem0", "letta", "memoirs"}),
    ("Use ReactNative for the mobile UI.",
     {"reactnative"}),
    ("Backend is Go with Redis caching and gRPC.",
     {"go", "redis"}),
    ("FastAPI service powered by uvicorn and Pydantic models.",
     {"fastapi"}),
    ("Indexing entities with spaCy and storing them in DuckDB.",
     {"duckdb"}),
    ("VSCode and Cursor both speak the LSP protocol.",
     {"vscode", "cursor"}),
    ("Claude Code calls our MCP server.",
     {"claude code", "mcp"}),
    ("The TypeScript SDK targets Node 20.",
     {"typescript", "node"}),
    ("Anthropic released Claude 3.7.",
     {"anthropic", "claude"}),
    ("OpenAI's GPT-4 vs Anthropic's Claude.",
     {"openai", "anthropic", "claude"}),
    ("We benchmarked Qwen3 against Phi-3.5.",
     set()),  # neither in our hint vocabulary
    ("Use `sqlite-vec` for ANN search.",
     {"sqlite-vec"}),
    ("Continue and Cursor are similar editor copilots.",
     {"cursor", "continue"}),
    ("Ingester pulls from Watchdog events.",
     {"watchdog"}),
    ("MemMachine and PowerMem competitors evaluated.",
     {"memmachine", "powermem"}),
    ("Switching from MySQL to Postgres.",
     {"mysql", "postgres"}),
    ("Rust crate uses tokio and serde.",
     {"rust"}),
    ("Generic prose with no real entities at all.", set()),
    ("Just a sentence about the weather and how it changes.", set()),
    ("Build with FastAPI on top of SQLAlchemy and Alembic.",
     {"fastapi"}),
    ("Embedded llama-cpp-python into a sidecar.",
     {"llama-cpp-python"}),
    ("Redis Streams power our event queue.",
     {"redis"}),
    ("We compared Memmachine, Letta, Zep and Mem0.",
     {"memmachine", "letta", "zep", "mem0"}),
    ("Cursor uses gpt-4 by default.", {"cursor"}),
    ("Backed by Chroma vector DB.", {"chroma"}),
    ("Switching to JavaScript runtime.", {"javascript"}),
    ("Bench against MentEDB.", {"mentedb"}),
]


# ----------------------------------------------------------------------
# Metrics
# ----------------------------------------------------------------------


@dataclass
class BinaryStats:
    """Stats for a yes/no decision against ground truth."""
    tp: int = 0
    tn: int = 0
    fp: int = 0
    fn: int = 0

    @property
    def total(self) -> int:
        return self.tp + self.tn + self.fp + self.fn

    @property
    def accuracy(self) -> float:
        n = self.total
        return (self.tp + self.tn) / n if n else 0.0

    @property
    def fpr(self) -> float:
        d = self.fp + self.tn
        return self.fp / d if d else 0.0

    @property
    def fnr(self) -> float:
        d = self.fn + self.tp
        return self.fn / d if d else 0.0


def _record(stats: BinaryStats, predicted: bool, truth: bool) -> None:
    if predicted and truth:
        stats.tp += 1
    elif not predicted and not truth:
        stats.tn += 1
    elif predicted and not truth:
        stats.fp += 1
    else:
        stats.fn += 1


def _percentile(values: list[float], pct: float) -> float:
    if not values:
        return 0.0
    s = sorted(values)
    k = max(0, min(len(s) - 1, int(round((pct / 100.0) * (len(s) - 1)))))
    return float(s[k])


def _summary(latencies_ms: list[float]) -> dict:
    if not latencies_ms:
        return {"n": 0, "mean_ms": 0.0, "p50_ms": 0.0, "p95_ms": 0.0}
    return {
        "n": len(latencies_ms),
        "mean_ms": round(statistics.mean(latencies_ms), 2),
        "p50_ms": round(_percentile(latencies_ms, 50), 2),
        "p95_ms": round(_percentile(latencies_ms, 95), 2),
    }


# ----------------------------------------------------------------------
# Layer A — lifecycle
# ----------------------------------------------------------------------


def _make_neighbor(content: str, ntype: str, age_days: int, sim: float,
                   *, usage: int = 0, score: float = 0.5) -> dict:
    created = datetime.now(timezone.utc) - timedelta(days=age_days)
    return {
        "id": f"mem-{abs(hash((content, ntype, age_days)))%10**8}",
        "type": ntype,
        "content": content,
        "created_at": created.isoformat(),
        "similarity": sim,
        "usage_count": usage,
        "score": score,
    }


def _llm_judge_expire(cand_content: str, neighbor_content: str,
                       *, llm_call: Callable[[str], str]) -> tuple[bool, str]:
    """Ask the LLM whether the neighbor is obsolete given the candidate.

    Returns (decision, raw_text). Falls back to False on parse failure.
    """
    prompt = (
        "Two statements about the same user. Decide if statement B is now "
        "OBSOLETE because statement A supersedes it (e.g. user moved, "
        "changed job, swapped technologies). Reply with ONLY one of:\n"
        "  YES\n"
        "  NO\n"
        f"A: {cand_content}\n"
        f"B: {neighbor_content}\n"
        "Answer:"
    )
    raw = llm_call(prompt)
    head = raw.strip().splitlines()[0].strip().upper() if raw.strip() else ""
    if head.startswith("YES"):
        return True, raw
    if head.startswith("NO"):
        return False, raw
    return False, raw


def _llm_judge_archive(content: str, age_days: int, usage: int, score: float, mtype: str,
                        *, llm_call: Callable[[str], str]) -> tuple[bool, str]:
    prompt = (
        "Decide if a stored memory should be ARCHIVED (no longer surfaced) "
        "given its metadata. Durable user preferences and important facts "
        "should NOT be archived even if dusty. Reply with ONLY YES or NO.\n"
        f"content: {content}\n"
        f"type: {mtype}\n"
        f"age_days: {age_days}\n"
        f"usage_count: {usage}\n"
        f"score: {score}\n"
        "Answer:"
    )
    raw = llm_call(prompt)
    head = raw.strip().splitlines()[0].strip().upper() if raw.strip() else ""
    if head.startswith("YES"):
        return True, raw
    if head.startswith("NO"):
        return False, raw
    return False, raw


def run_layer_a(cases_expire: list, cases_archive: list,
                *, llm_call: Callable[[str], str] | None) -> dict:
    """Run EXPIRE + ARCHIVE A/B."""
    from memoirs.engine.lifecycle_decisions import should_expire, should_archive
    from memoirs.engine.curator import Candidate

    out: dict = {}

    # ---- EXPIRE ----
    h_stats = BinaryStats()
    l_stats = BinaryStats()
    agree = 0
    h_lat: list[float] = []
    l_lat: list[float] = []
    examples: list[dict] = []

    for (cc, ct, nc, nt, age, sim, gt) in cases_expire:
        cand = Candidate(type=ct, content=cc)
        nb = _make_neighbor(nc, nt, age, sim)
        t0 = time.perf_counter()
        h_pred, h_reason = should_expire(cand, nb, use_gemma=False)
        h_lat.append((time.perf_counter() - t0) * 1000)

        if llm_call is not None:
            t0 = time.perf_counter()
            l_pred, _l_raw = _llm_judge_expire(cc, nc, llm_call=llm_call)
            l_lat.append((time.perf_counter() - t0) * 1000)
        else:
            l_pred = None

        _record(h_stats, h_pred, gt)
        if l_pred is not None:
            _record(l_stats, l_pred, gt)
            if h_pred == l_pred:
                agree += 1
        if len(examples) < 8:
            examples.append({
                "candidate": cc, "neighbor": nc, "age_d": age, "sim": sim,
                "ground_truth": gt, "heuristic": h_pred, "llm": l_pred,
            })

    out["expire"] = {
        "n": len(cases_expire),
        "heuristic": {
            **{"accuracy": round(h_stats.accuracy, 3),
               "fpr": round(h_stats.fpr, 3),
               "fnr": round(h_stats.fnr, 3)},
            **asdict(h_stats),
            "latency": _summary(h_lat),
        },
        "llm": (
            {**{"accuracy": round(l_stats.accuracy, 3),
                "fpr": round(l_stats.fpr, 3),
                "fnr": round(l_stats.fnr, 3)},
             **asdict(l_stats),
             "latency": _summary(l_lat)}
            if llm_call is not None else None
        ),
        "agreement_rate": (
            round(agree / len(cases_expire), 3)
            if llm_call is not None and cases_expire else None
        ),
        "examples": examples,
    }

    # ---- ARCHIVE ----
    h_stats = BinaryStats()
    l_stats = BinaryStats()
    agree = 0
    h_lat = []
    l_lat = []
    examples = []

    for (content, age, usage, score, mtype, gt) in cases_archive:
        nb = _make_neighbor(content, mtype, age, 0.0, usage=usage, score=score)
        t0 = time.perf_counter()
        h_pred, _h_reason = should_archive(nb)
        h_lat.append((time.perf_counter() - t0) * 1000)

        if llm_call is not None:
            t0 = time.perf_counter()
            l_pred, _l_raw = _llm_judge_archive(
                content, age, usage, score, mtype, llm_call=llm_call,
            )
            l_lat.append((time.perf_counter() - t0) * 1000)
        else:
            l_pred = None

        _record(h_stats, h_pred, gt)
        if l_pred is not None:
            _record(l_stats, l_pred, gt)
            if h_pred == l_pred:
                agree += 1
        if len(examples) < 8:
            examples.append({
                "content": content, "age_d": age, "usage": usage, "score": score,
                "type": mtype, "ground_truth": gt, "heuristic": h_pred, "llm": l_pred,
            })

    out["archive"] = {
        "n": len(cases_archive),
        "heuristic": {
            **{"accuracy": round(h_stats.accuracy, 3),
               "fpr": round(h_stats.fpr, 3),
               "fnr": round(h_stats.fnr, 3)},
            **asdict(h_stats),
            "latency": _summary(h_lat),
        },
        "llm": (
            {**{"accuracy": round(l_stats.accuracy, 3),
                "fpr": round(l_stats.fpr, 3),
                "fnr": round(l_stats.fnr, 3)},
             **asdict(l_stats),
             "latency": _summary(l_lat)}
            if llm_call is not None else None
        ),
        "agreement_rate": (
            round(agree / len(cases_archive), 3)
            if llm_call is not None and cases_archive else None
        ),
        "examples": examples,
    }

    return out


# ----------------------------------------------------------------------
# Layer B — consolidate
# ----------------------------------------------------------------------


class _StubDB:
    """Tiny stand-in for MemoirsDB that pretends to know about a fixed set
    of neighbors. Lets us drive `_heuristic_decide_memory_action` without
    spinning up a real SQLite + embeddings.
    """

    def __init__(self, neighbors: list[tuple[str, str, float]]):
        # neighbors = [(content, type, sim), ...] (most similar first)
        self.neighbors = neighbors


def _heuristic_consolidate(cand_content: str, cand_type: str,
                            neighbors: list[tuple[str, str, float]]) -> str:
    """Reproduce the heuristic curator decision tree without DB plumbing.

    Mirrors `_heuristic_decide_memory_action` exactly:
      - empty content → IGNORE
      - noise filter → REJECT (we coalesce REJECT→IGNORE in the bench)
      - exact match same type → UPDATE
      - exact match cross type → MERGE
      - sim ≥ 0.85 same type → MERGE
      - sim ≥ 0.85 different type → CONTRADICTION
      - else ADD
    """
    from memoirs.core.normalize import should_skip_extraction

    if not cand_content.strip():
        return "IGNORE"
    skip, _ = should_skip_extraction(cand_content)
    if skip:
        return "IGNORE"  # coalesce REJECT into IGNORE for ground-truth label

    cand_norm = cand_content.strip().lower()
    for nc, nt, sim in neighbors:
        if nc.strip().lower() == cand_norm:
            return "UPDATE" if nt == cand_type else "MERGE"

    SEM_THRESH = 0.85
    for nc, nt, sim in neighbors:
        if sim >= SEM_THRESH:
            return "MERGE" if nt == cand_type else "CONTRADICTION"

    return "ADD"


def _llm_consolidate_judge(cand_content: str, cand_type: str,
                            neighbors: list[tuple[str, str, float]],
                            *, llm_call: Callable[[str], str]) -> str:
    if not cand_content.strip():
        return "IGNORE"
    nb_block = (
        "\n".join(f"  - [{nt}] {nc} (sim={sim:.2f})" for nc, nt, sim in neighbors)
        if neighbors else "  (none)"
    )
    prompt = (
        "Decide what to do with a new memoria candidate against existing "
        "neighbors. Reply with ONE of: ADD, UPDATE, MERGE, IGNORE, CONTRADICTION.\n"
        f"Candidate: [{cand_type}] {cand_content}\n"
        "Neighbors:\n"
        f"{nb_block}\n"
        "Decision:"
    )
    raw = llm_call(prompt)
    head = raw.strip().splitlines()[0].strip().upper() if raw.strip() else ""
    for tok in ("UPDATE", "MERGE", "CONTRADICTION", "IGNORE", "ADD"):
        if tok in head:
            return tok
    return "ADD"


def run_layer_b(cases: list, *, llm_call: Callable[[str], str] | None) -> dict:
    h_correct = 0
    l_correct = 0
    agree = 0
    confusion_h: dict = {}
    confusion_l: dict = {}
    h_lat: list[float] = []
    l_lat: list[float] = []
    examples: list[dict] = []

    for (cc, ct, nbs, gt) in cases:
        t0 = time.perf_counter()
        h_pred = _heuristic_consolidate(cc, ct, nbs)
        h_lat.append((time.perf_counter() - t0) * 1000)

        if llm_call is not None:
            t0 = time.perf_counter()
            l_pred = _llm_consolidate_judge(cc, ct, nbs, llm_call=llm_call)
            l_lat.append((time.perf_counter() - t0) * 1000)
        else:
            l_pred = None

        if h_pred == gt:
            h_correct += 1
        confusion_h.setdefault(gt, {}).setdefault(h_pred, 0)
        confusion_h[gt][h_pred] += 1
        if l_pred is not None:
            if l_pred == gt:
                l_correct += 1
            confusion_l.setdefault(gt, {}).setdefault(l_pred, 0)
            confusion_l[gt][l_pred] += 1
            if h_pred == l_pred:
                agree += 1

        if len(examples) < 10:
            examples.append({
                "candidate": cc, "type": ct, "n_neighbors": len(nbs),
                "ground_truth": gt, "heuristic": h_pred, "llm": l_pred,
            })

    n = len(cases)
    return {
        "n": n,
        "heuristic": {
            "accuracy": round(h_correct / n, 3) if n else 0.0,
            "correct": h_correct,
            "confusion": confusion_h,
            "latency": _summary(h_lat),
        },
        "llm": (
            {"accuracy": round(l_correct / n, 3) if n else 0.0,
             "correct": l_correct,
             "confusion": confusion_l,
             "latency": _summary(l_lat)}
            if llm_call is not None else None
        ),
        "agreement_rate": (
            round(agree / n, 3) if llm_call is not None and n else None
        ),
        "examples": examples,
    }


# ----------------------------------------------------------------------
# Layer C — entity extraction
# ----------------------------------------------------------------------


def _ent_metrics(predicted: set[str], truth: set[str]) -> dict:
    if not predicted and not truth:
        return {"precision": 1.0, "recall": 1.0, "f1": 1.0,
                "tp": 0, "fp": 0, "fn": 0}
    tp = len(predicted & truth)
    fp = len(predicted - truth)
    fn = len(truth - predicted)
    precision = tp / (tp + fp) if (tp + fp) else (1.0 if not truth else 0.0)
    recall = tp / (tp + fn) if (tp + fn) else 1.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0
    return {"precision": round(precision, 3), "recall": round(recall, 3),
            "f1": round(f1, 3), "tp": tp, "fp": fp, "fn": fn}


def _llm_judge_entities(text: str,
                         *, llm_call: Callable[[str], str]) -> set[str]:
    prompt = (
        "Extract named entities (tools, projects, technologies, people). "
        "Output ONLY a comma-separated list of names, lowercased. No prose.\n"
        f"Text: {text}\n"
        "Entities:"
    )
    raw = llm_call(prompt)
    line = raw.strip().splitlines()[0].strip() if raw.strip() else ""
    out = {p.strip().lower() for p in line.split(",") if p.strip()}
    out = {n for n in out if 2 <= len(n) <= 40}
    return out


def run_layer_c(cases: list, *, llm_call: Callable[[str], str] | None) -> dict:
    from memoirs.engine.graph import _extract_entities_heuristic

    h_p: list[float] = []
    h_r: list[float] = []
    h_f: list[float] = []
    l_p: list[float] = []
    l_r: list[float] = []
    l_f: list[float] = []
    h_lat: list[float] = []
    l_lat: list[float] = []
    agree_per_case: list[float] = []
    examples: list[dict] = []

    for (text, expected) in cases:
        t0 = time.perf_counter()
        h_ents = {n.lower() for (n, _t) in _extract_entities_heuristic(text)}
        h_lat.append((time.perf_counter() - t0) * 1000)
        h_m = _ent_metrics(h_ents, expected)
        h_p.append(h_m["precision"])
        h_r.append(h_m["recall"])
        h_f.append(h_m["f1"])

        if llm_call is not None:
            t0 = time.perf_counter()
            l_ents = _llm_judge_entities(text, llm_call=llm_call)
            l_lat.append((time.perf_counter() - t0) * 1000)
            l_m = _ent_metrics(l_ents, expected)
            l_p.append(l_m["precision"])
            l_r.append(l_m["recall"])
            l_f.append(l_m["f1"])
            inter = h_ents & l_ents
            union = h_ents | l_ents
            agree_per_case.append(len(inter) / len(union) if union else 1.0)
        else:
            l_ents = None

        if len(examples) < 10:
            examples.append({
                "text": text[:80],
                "expected": sorted(expected),
                "heuristic": sorted(h_ents),
                "llm": sorted(l_ents) if l_ents is not None else None,
                "h_f1": h_m["f1"],
            })

    def _avg(xs: list[float]) -> float:
        return round(sum(xs) / len(xs), 3) if xs else 0.0

    return {
        "n": len(cases),
        "heuristic": {
            "precision_mean": _avg(h_p),
            "recall_mean": _avg(h_r),
            "f1_mean": _avg(h_f),
            "latency": _summary(h_lat),
        },
        "llm": (
            {"precision_mean": _avg(l_p),
             "recall_mean": _avg(l_r),
             "f1_mean": _avg(l_f),
             "latency": _summary(l_lat)}
            if llm_call is not None else None
        ),
        "agreement_jaccard_mean": (
            round(sum(agree_per_case) / len(agree_per_case), 3)
            if llm_call is not None and agree_per_case else None
        ),
        "examples": examples,
    }


# ----------------------------------------------------------------------
# LLM backends
# ----------------------------------------------------------------------


def _build_qwen_caller():
    """Load the local Qwen GGUF and return a `lambda prompt: text` callable.

    Returns None if llama_cpp / weights are missing.
    """
    try:
        from memoirs.engine import curator as _c
    except Exception:
        return None
    if not _c._have_curator():
        return None
    try:
        llm = _c._get_llm()
    except Exception as e:
        log.warning("qwen load failed: %s", e)
        return None

    def _call(prompt: str) -> str:
        body = _c._chat_user_turn(prompt)
        try:
            out = llm.create_completion(
                prompt=body,
                max_tokens=80,
                temperature=0.1,
                stop=_c._chat_stops(),
            )
        except Exception as e:
            log.warning("qwen call raised: %s", e)
            return ""
        return (out.get("choices", [{}])[0].get("text") or "").strip()

    return _call


def _build_openai_caller(model: str = "gpt-4o-mini"):
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return None
    try:
        from openai import OpenAI
    except Exception:
        log.warning("openai SDK not installed")
        return None
    client = OpenAI(api_key=api_key)

    def _call(prompt: str) -> str:
        try:
            resp = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                max_tokens=80,
            )
            return (resp.choices[0].message.content or "").strip()
        except Exception as e:
            log.warning("openai call raised: %s", e)
            return ""

    return _call


# ----------------------------------------------------------------------
# Reporting
# ----------------------------------------------------------------------


def _print_table(report: dict) -> None:
    print()
    print("=" * 78)
    print("A/B benchmark: heuristic vs LLM curator")
    print("=" * 78)
    for layer in ("layer_a", "layer_b", "layer_c"):
        sub = report.get(layer)
        if not sub:
            continue
        print(f"\n[{layer.upper()}] {sub.get('description', '')}")
        for sec_name, sec in sub.get("sections", {}).items():
            print(f"  · {sec_name} (n={sec['n']})")
            h = sec["heuristic"]
            l = sec.get("llm")
            print(
                f"    heuristic: " + ", ".join(
                    f"{k}={v}" for k, v in h.items() if k != "latency"
                )[:200]
            )
            print(f"      latency: {h['latency']}")
            if l is not None:
                print(
                    f"    llm:       " + ", ".join(
                        f"{k}={v}" for k, v in l.items() if k != "latency"
                    )[:200]
                )
                print(f"      latency: {l['latency']}")
                if "agreement_rate" in sec and sec["agreement_rate"] is not None:
                    print(f"    agreement: {sec['agreement_rate']}")
                if "agreement_jaccard_mean" in sec and sec.get("agreement_jaccard_mean") is not None:
                    print(f"    jaccard:   {sec['agreement_jaccard_mean']}")
    rec = report.get("recommendation")
    if rec:
        print("\nRecommendation:")
        for line in rec.splitlines():
            print(f"  {line}")
    print("=" * 78)


def _recommendation(report: dict) -> str:
    """Crude rule-of-thumb verdict per layer based on accuracy delta."""
    lines: list[str] = []
    a = report.get("layer_a", {}).get("sections", {})
    b = report.get("layer_b", {}).get("sections", {})
    c = report.get("layer_c", {}).get("sections", {})

    def _verdict(h_acc: float | None, l_acc: float | None,
                  h_p95: float, l_p95: float, label: str) -> str:
        if l_acc is None or h_acc is None:
            return f"{label}: heuristic only (LLM not available)"
        delta = l_acc - h_acc
        slowdown = (l_p95 / h_p95) if h_p95 > 0 else float("inf")
        if delta > 0.10:
            return (f"{label}: LLM wins (+{delta:.2f} acc, {slowdown:.0f}x slower) "
                    "→ keep heuristic default + LLM opt-in for high-stakes paths")
        if delta < -0.05:
            return (f"{label}: heuristic wins ({-delta:.2f} better, "
                    f"{slowdown:.0f}x faster) → keep heuristic")
        return (f"{label}: tie (Δacc={delta:+.2f}); heuristic is "
                f"{slowdown:.0f}x faster → keep heuristic")

    if a:
        for k in ("expire", "archive"):
            sec = a.get(k)
            if not sec:
                continue
            h = sec["heuristic"]
            l = sec.get("llm")
            lines.append(_verdict(
                h.get("accuracy"),
                (l or {}).get("accuracy"),
                h.get("latency", {}).get("p95_ms", 0),
                (l or {}).get("latency", {}).get("p95_ms", 0),
                f"A.{k}",
            ))
    if b:
        sec = b.get("consolidate")
        if sec:
            h = sec["heuristic"]; l = sec.get("llm")
            lines.append(_verdict(
                h.get("accuracy"),
                (l or {}).get("accuracy"),
                h.get("latency", {}).get("p95_ms", 0),
                (l or {}).get("latency", {}).get("p95_ms", 0),
                "B.consolidate",
            ))
    if c:
        sec = c.get("entities")
        if sec:
            h = sec["heuristic"]; l = sec.get("llm")
            lines.append(_verdict(
                h.get("f1_mean"),
                (l or {}).get("f1_mean"),
                h.get("latency", {}).get("p95_ms", 0),
                (l or {}).get("latency", {}).get("p95_ms", 0),
                "C.entities",
            ))
    if not lines:
        lines.append("no layers run")
    return "\n".join(lines)


# ----------------------------------------------------------------------
# Public entrypoint (also called from tests)
# ----------------------------------------------------------------------


def run_benchmark(*, layers: set[str], n_per_layer: int | None,
                   llm_call: Callable[[str], str] | None) -> dict:
    expire_cases = EXPIRE_CASES if n_per_layer is None else EXPIRE_CASES[:n_per_layer]
    archive_cases = ARCHIVE_CASES if n_per_layer is None else ARCHIVE_CASES[:n_per_layer]
    consolidate_cases = (CONSOLIDATE_CASES if n_per_layer is None
                          else CONSOLIDATE_CASES[:n_per_layer])
    entity_cases = ENTITY_CASES if n_per_layer is None else ENTITY_CASES[:n_per_layer]

    report: dict = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "n_per_layer": n_per_layer,
        "llm_used": llm_call is not None,
    }

    if "A" in layers:
        a = run_layer_a(expire_cases, archive_cases, llm_call=llm_call)
        report["layer_a"] = {
            "description": "lifecycle_decisions: should_expire / should_archive",
            "sections": a,
        }
    if "B" in layers:
        b = run_layer_b(consolidate_cases, llm_call=llm_call)
        report["layer_b"] = {
            "description": "memory_engine._heuristic_decide_memory_action vs curator_consolidate",
            "sections": {"consolidate": b},
        }
    if "C" in layers:
        c = run_layer_c(entity_cases, llm_call=llm_call)
        report["layer_c"] = {
            "description": "graph._extract_entities_heuristic vs curator_extract_entities",
            "sections": {"entities": c},
        }

    report["recommendation"] = _recommendation(report)
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layer", choices=("A", "B", "C", "all"), default="all")
    parser.add_argument("--smoke", action="store_true",
                        help="10 cases per layer instead of 30")
    parser.add_argument("--full", action="store_true",
                        help="Use the entire hand-graded set per layer")
    parser.add_argument("--no-llm", action="store_true",
                        help="Skip the LLM side; run heuristic only")
    parser.add_argument("--openai", action="store_true",
                        help="Use OpenAI as LLM judge (requires OPENAI_API_KEY)")
    parser.add_argument("--openai-model", default="gpt-4o-mini")
    parser.add_argument("--out", default=".memoirs/heuristic_vs_llm_quality.json")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.WARNING if args.quiet else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    if args.smoke:
        n = 10
    elif args.full:
        n = None
    else:
        n = 30

    layers = {"A", "B", "C"} if args.layer == "all" else {args.layer}

    llm_call = None
    if not args.no_llm:
        if args.openai:
            llm_call = _build_openai_caller(args.openai_model)
            if llm_call is None:
                log.warning("OpenAI requested but unavailable; running heuristic only")
        else:
            llm_call = _build_qwen_caller()
            if llm_call is None and os.environ.get("OPENAI_API_KEY"):
                log.info("Qwen unavailable; falling back to OpenAI")
                llm_call = _build_openai_caller(args.openai_model)
            if llm_call is None:
                log.warning("No LLM available; running heuristic only")

    report = run_benchmark(layers=layers, n_per_layer=n, llm_call=llm_call)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, indent=2))
    if not args.quiet:
        _print_table(report)
        print(f"\nReport written to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
