"""GDPR-compliant data export and portable import (P3-6).

This module produces a self-describing zip bundle of the entire memoirs
corpus so users can take their data elsewhere (right of portability) or
move it between machines. The reverse operation re-hydrates a fresh DB
from a previously emitted bundle.

Bundle layout
-------------

    bundle.zip
    ├── manifest.json              schema_version, timestamp, counts, sha256
    ├── README.md                  human-friendly description (autogenerated)
    ├── memories.jsonl             one memory row per line (full columns)
    ├── conversations/
    │   └── <conv_id>.jsonl        messages + conversation header per line
    ├── embeddings.npz             np.savez(memory_id=…, vector=…) (optional)
    ├── entities.jsonl
    ├── relationships.jsonl
    ├── memory_links.jsonl
    ├── summary_nodes.jsonl
    └── provenance.jsonl           memory_id → source/conversation/messages

Notes
-----
- ``user_id`` is honoured if the column exists on the ``memories`` table
  (a future migration may introduce it). When the column is absent — the
  current default — the filter is silently ignored and we export the
  whole corpus, as instructed by the GAP P3-6 task.
- ``schema_version`` in the manifest is the ``PRAGMA user_version`` of
  the source DB; the importer uses it to detect mismatches.
- All file content is hashed with sha256 *before* zipping so
  :func:`verify_bundle` can detect tampering without unpacking the data
  itself.
"""
from __future__ import annotations

import hashlib
import io
import json
import logging
import sqlite3
import struct
import zipfile
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Literal, Optional

from .core.redact import redact
from .db import MemoirsDB
from .migrations import current_version, target_version


log = logging.getLogger("memoirs.export")


SCHEMA_VERSION = 1
"""Bundle layout version. Bump when files / fields change incompatibly."""

ImportMode = Literal["merge", "replace", "new_user"]


# ---------------------------------------------------------------------------
# Manifest dataclass
# ---------------------------------------------------------------------------


@dataclass
class ExportManifest:
    schema_version: int
    db_user_version: int
    timestamp: str
    user_id: Optional[str]
    redact_pii: bool
    counts: dict[str, int]
    files: dict[str, dict[str, Any]]  # name -> {sha256, size}
    bundle_path: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "db_user_version": self.db_user_version,
            "timestamp": self.timestamp,
            "user_id": self.user_id,
            "redact_pii": self.redact_pii,
            "counts": dict(self.counts),
            "files": {k: dict(v) for k, v in self.files.items()},
            "bundle_path": self.bundle_path,
        }


@dataclass
class ImportReport:
    schema_version: int
    db_user_version: int
    mode: str
    user_id_target: Optional[str]
    inserted: dict[str, int] = field(default_factory=dict)
    skipped: dict[str, int] = field(default_factory=dict)
    deleted: dict[str, int] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Schema introspection
# ---------------------------------------------------------------------------


def _has_table(conn: sqlite3.Connection, name: str) -> bool:
    row = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)
    ).fetchone()
    return row is not None


def _has_column(conn: sqlite3.Connection, table: str, column: str) -> bool:
    if not _has_table(conn, table):
        return False
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(r[1] == column for r in rows)


def _column_names(conn: sqlite3.Connection, table: str) -> list[str]:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return [r[1] for r in rows]


def _row_to_dict(row: sqlite3.Row) -> dict[str, Any]:
    return {k: row[k] for k in row.keys()}


# ---------------------------------------------------------------------------
# Helpers: redaction + serialization
# ---------------------------------------------------------------------------


def anonymize_memory(memory: dict[str, Any]) -> dict[str, Any]:
    """Apply :func:`redact` to every string-typed value of ``memory``.

    Wrapper kept lightweight — does not touch JSON-encoded blobs by design;
    callers wanting deeper redaction can post-process metadata_json themselves.
    """
    out = dict(memory)
    for key, value in list(out.items()):
        if isinstance(value, str) and value:
            try:
                out[key] = redact(value).text
            except Exception:  # pragma: no cover — defensive
                pass
    return out


def _redact_message(msg: dict[str, Any]) -> dict[str, Any]:
    out = dict(msg)
    for key in ("content", "raw_json", "metadata_json"):
        val = out.get(key)
        if isinstance(val, str) and val:
            try:
                out[key] = redact(val).text
            except Exception:  # pragma: no cover
                pass
    return out


# ---------------------------------------------------------------------------
# Hash helper for the manifest
# ---------------------------------------------------------------------------


def _sha256_bytes(data: bytes) -> str:
    h = hashlib.sha256()
    h.update(data)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# JSONL writer (in-memory, returns bytes for the zip)
# ---------------------------------------------------------------------------


def _jsonl_bytes(rows: Iterable[dict[str, Any]]) -> bytes:
    buf = io.StringIO()
    for r in rows:
        buf.write(json.dumps(r, ensure_ascii=False, sort_keys=True))
        buf.write("\n")
    return buf.getvalue().encode("utf-8")


# ---------------------------------------------------------------------------
# Embedding pack helpers (mirrors engine.embeddings._unpack semantics)
# ---------------------------------------------------------------------------


def _embeddings_to_npz(rows: list[dict[str, Any]]) -> bytes:
    """Pack memory embeddings into a numpy .npz blob.

    Each row is ``{memory_id, dim, embedding (BLOB), model, created_at}``.
    The .npz contains two parallel arrays: ``memory_ids`` (object) and
    ``vectors`` (float32, shape (N, dim)). When dimensions vary we store
    a list-of-arrays via numpy object dtype.
    """
    import numpy as np  # local: only loaded when bundling embeddings

    if not rows:
        # Empty placeholder still usable for round-trip; np.savez with no
        # arrays writes an empty zip which the importer handles.
        buf = io.BytesIO()
        np.savez(buf, memory_ids=np.array([], dtype=object), vectors=np.array([]))
        return buf.getvalue()

    dims = {int(r["dim"]) for r in rows}
    ids = np.array([r["memory_id"] for r in rows], dtype=object)
    models = np.array([r.get("model") or "" for r in rows], dtype=object)
    created = np.array([r.get("created_at") or "" for r in rows], dtype=object)

    if len(dims) == 1:
        dim = next(iter(dims))
        vectors = np.zeros((len(rows), dim), dtype=np.float32)
        for i, r in enumerate(rows):
            blob = r["embedding"] or b""
            if len(blob) != dim * 4:
                raise ValueError(
                    f"embedding for {r['memory_id']} has wrong size "
                    f"({len(blob)} bytes, expected {dim * 4})"
                )
            vectors[i] = np.frombuffer(blob, dtype=np.float32)
        buf = io.BytesIO()
        np.savez(
            buf,
            memory_ids=ids,
            vectors=vectors,
            models=models,
            created_at=created,
            dim=np.array([dim], dtype=np.int64),
        )
        return buf.getvalue()

    # Mixed-dim corner case (shouldn't really happen): store as object array.
    vec_objs = np.empty(len(rows), dtype=object)
    dim_arr = np.zeros(len(rows), dtype=np.int64)
    for i, r in enumerate(rows):
        blob = r["embedding"] or b""
        d = int(r["dim"])
        dim_arr[i] = d
        vec_objs[i] = np.frombuffer(blob, dtype=np.float32).copy()
    buf = io.BytesIO()
    np.savez(
        buf,
        memory_ids=ids,
        vectors=vec_objs,
        models=models,
        created_at=created,
        dim=dim_arr,
    )
    return buf.getvalue()


def _npz_to_embeddings(blob: bytes) -> list[dict[str, Any]]:
    """Inverse of :func:`_embeddings_to_npz`."""
    import numpy as np

    buf = io.BytesIO(blob)
    npz = np.load(buf, allow_pickle=True)
    ids = npz.get("memory_ids")
    if ids is None or len(ids) == 0:
        return []
    vectors = npz["vectors"]
    models = npz.get("models")
    created = npz.get("created_at")
    dim_arr = npz.get("dim")

    out: list[dict[str, Any]] = []
    if vectors.dtype == object:
        # mixed dim path
        for i, mid in enumerate(ids):
            v = np.asarray(vectors[i], dtype=np.float32)
            d = int(dim_arr[i]) if dim_arr is not None else int(v.shape[0])
            out.append({
                "memory_id": str(mid),
                "dim": d,
                "embedding": v.tobytes(),
                "model": str(models[i]) if models is not None and i < len(models) else "",
                "created_at": str(created[i]) if created is not None and i < len(created) else "",
            })
    else:
        d = int(vectors.shape[1]) if vectors.ndim == 2 else int(dim_arr[0]) if dim_arr is not None else 0
        for i, mid in enumerate(ids):
            v = np.asarray(vectors[i], dtype=np.float32)
            out.append({
                "memory_id": str(mid),
                "dim": d,
                "embedding": v.tobytes(),
                "model": str(models[i]) if models is not None and i < len(models) else "",
                "created_at": str(created[i]) if created is not None and i < len(created) else "",
            })
    return out


# ---------------------------------------------------------------------------
# README
# ---------------------------------------------------------------------------


_README_TEMPLATE = """# Memoirs export bundle

This zip is a portable snapshot of a memoirs corpus, produced by
``memoirs export``. It conforms to bundle schema_version={schema_version}
and was emitted at {timestamp} (UTC).

## Contents

- ``manifest.json`` — counts + sha256 hash for every other file in this bundle.
- ``memories.jsonl`` — one memory per line, full row.
- ``conversations/<conv_id>.jsonl`` — conversation header (ordinal=-1) followed
  by every active message in ordinal order.
- ``entities.jsonl``, ``relationships.jsonl`` — knowledge graph (Layer 3).
- ``memory_links.jsonl`` — A-MEM Zettelkasten edges (P1-3).
- ``summary_nodes.jsonl`` — RAPTOR summary tree (P1-6) when present.
- ``embeddings.npz`` — parallel arrays ``memory_ids`` / ``vectors``
  (float32). Absent when ``--no-embeddings`` was passed.
- ``provenance.jsonl`` — memory_id → source URI / conversation / messages.

## Re-import

    memoirs import path/to/this.zip --mode merge      # add, skip duplicates
    memoirs import path/to/this.zip --mode replace    # wipe + restore
    memoirs import path/to/this.zip --mode new_user --new-user-id alice

## Verify

    memoirs export verify path/to/this.zip
"""


def _render_readme(schema_version: int, timestamp: str) -> str:
    return _README_TEMPLATE.format(schema_version=schema_version, timestamp=timestamp)


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------


def _filter_by_user_id(
    conn: sqlite3.Connection, user_id: Optional[str]
) -> tuple[str, tuple[Any, ...]]:
    """Return (where_clause, params) honoring the ``user_id`` filter.

    Falls back to ``("", ())`` when the column does not exist (current default
    schema) or when ``user_id`` is None — exporting the whole corpus.
    """
    if user_id is None:
        return "", ()
    if not _has_column(conn, "memories", "user_id"):
        log.info("memories.user_id column not present — exporting whole corpus")
        return "", ()
    return " WHERE user_id = ?", (user_id,)


def export_user_data(
    db: MemoirsDB,
    *,
    user_id: Optional[str] = "local",
    out_path: Path,
    include_embeddings: bool = True,
    redact_pii: bool = False,
    compression: int = zipfile.ZIP_DEFLATED,
) -> ExportManifest:
    """Export the memoirs corpus to ``out_path`` (a zip file).

    Parameters
    ----------
    db
        Open :class:`MemoirsDB`.
    user_id
        When the ``memories`` table has a ``user_id`` column, only rows
        matching this id are exported. Pass ``None`` to ignore the filter
        explicitly. With the current default schema the column is absent,
        so the whole corpus is dumped regardless of this argument.
    out_path
        Destination zip file. Parent directories are created on demand.
    include_embeddings
        When False, ``embeddings.npz`` is omitted from the bundle.
    redact_pii
        When True, every textual field is passed through
        :func:`memoirs.core.redact.redact` before serialization. Hashes,
        ids, and timestamps are left intact.
    compression
        ``zipfile.ZIP_DEFLATED`` (default) or ``zipfile.ZIP_STORED``.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    conn = db.conn
    where_mem, mem_params = _filter_by_user_id(conn, user_id)

    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    files: dict[str, bytes] = {}
    counts: dict[str, int] = {}

    # ---- memories ---------------------------------------------------------
    mem_cols = _column_names(conn, "memories")
    mem_rows = [
        _row_to_dict(r)
        for r in conn.execute(f"SELECT * FROM memories{where_mem}", mem_params).fetchall()
    ]
    if redact_pii:
        mem_rows = [anonymize_memory(m) for m in mem_rows]
    files["memories.jsonl"] = _jsonl_bytes(mem_rows)
    counts["memories"] = len(mem_rows)

    memory_ids = {m["id"] for m in mem_rows}

    # ---- conversations + messages ----------------------------------------
    conv_rows = [_row_to_dict(r) for r in conn.execute("SELECT * FROM conversations").fetchall()]
    msg_rows = [
        _row_to_dict(r)
        for r in conn.execute(
            "SELECT * FROM messages ORDER BY conversation_id, ordinal"
        ).fetchall()
    ]
    if redact_pii:
        msg_rows = [_redact_message(m) for m in msg_rows]

    by_conv: dict[str, list[dict[str, Any]]] = {}
    for m in msg_rows:
        by_conv.setdefault(m["conversation_id"], []).append(m)

    counts["conversations"] = len(conv_rows)
    counts["messages"] = len(msg_rows)
    for conv in conv_rows:
        cid = conv["id"]
        # First line is the header (ordinal=-1 marker); the rest are messages
        # in ordinal order. The importer keys on ``conversation_id`` only.
        header = {"__type__": "conversation", **conv}
        msgs = by_conv.get(cid, [])
        body = [header] + [{"__type__": "message", **m} for m in msgs]
        files[f"conversations/{cid}.jsonl"] = _jsonl_bytes(body)

    # ---- sources (referenced by FK from conversations) -------------------
    src_rows = [_row_to_dict(r) for r in conn.execute("SELECT * FROM sources").fetchall()]
    files["sources.jsonl"] = _jsonl_bytes(src_rows)
    counts["sources"] = len(src_rows)

    # ---- embeddings -------------------------------------------------------
    if include_embeddings:
        emb_rows = [
            _row_to_dict(r)
            for r in conn.execute(
                "SELECT memory_id, dim, embedding, model, created_at "
                "FROM memory_embeddings"
            ).fetchall()
        ]
        # Filter to exported memories only.
        emb_rows = [r for r in emb_rows if r["memory_id"] in memory_ids]
        files["embeddings.npz"] = _embeddings_to_npz(emb_rows)
        counts["embeddings"] = len(emb_rows)
    else:
        counts["embeddings"] = 0

    # ---- entities + memory_entities + relationships ---------------------
    ent_rows = [_row_to_dict(r) for r in conn.execute("SELECT * FROM entities").fetchall()]
    files["entities.jsonl"] = _jsonl_bytes(ent_rows)
    counts["entities"] = len(ent_rows)

    me_rows = [
        _row_to_dict(r) for r in conn.execute("SELECT * FROM memory_entities").fetchall()
    ]
    files["memory_entities.jsonl"] = _jsonl_bytes(me_rows)
    counts["memory_entities"] = len(me_rows)

    rel_rows = [
        _row_to_dict(r) for r in conn.execute("SELECT * FROM relationships").fetchall()
    ]
    files["relationships.jsonl"] = _jsonl_bytes(rel_rows)
    counts["relationships"] = len(rel_rows)

    # ---- memory_links (P1-3) — table exists from migration 002 ----------
    if _has_table(conn, "memory_links"):
        link_rows = [
            _row_to_dict(r)
            for r in conn.execute(
                "SELECT source_memory_id, target_memory_id, similarity, reason, created_at "
                "FROM memory_links"
            ).fetchall()
        ]
        files["memory_links.jsonl"] = _jsonl_bytes(link_rows)
        counts["memory_links"] = len(link_rows)
    else:
        files["memory_links.jsonl"] = b""
        counts["memory_links"] = 0

    # ---- summary nodes (P1-6) ------------------------------------------
    if _has_table(conn, "summary_nodes"):
        sn_rows = [
            _row_to_dict(r)
            for r in conn.execute(
                "SELECT id, level, content, child_count, created_at, parent_id, "
                "scope_kind, scope_id FROM summary_nodes"
            ).fetchall()
        ]
        files["summary_nodes.jsonl"] = _jsonl_bytes(sn_rows)
        counts["summary_nodes"] = len(sn_rows)
        if _has_table(conn, "summary_node_members"):
            mem_link_rows = [
                _row_to_dict(r)
                for r in conn.execute("SELECT * FROM summary_node_members").fetchall()
            ]
            files["summary_node_members.jsonl"] = _jsonl_bytes(mem_link_rows)
            counts["summary_node_members"] = len(mem_link_rows)
    else:
        files["summary_nodes.jsonl"] = b""
        counts["summary_nodes"] = 0

    # ---- provenance: memory_id → source/conversation/messages ----------
    # We derive provenance from memory_candidates.source_message_ids when
    # available. ``source_message_ids`` is a JSON array of message ids.
    prov_rows: list[dict[str, Any]] = []
    if _has_table(conn, "memory_candidates"):
        cand_rows = conn.execute(
            "SELECT promoted_memory_id, conversation_id, source_message_ids "
            "FROM memory_candidates "
            "WHERE promoted_memory_id IS NOT NULL"
        ).fetchall()
        for r in cand_rows:
            mid = r["promoted_memory_id"]
            if mid not in memory_ids:
                continue
            try:
                msg_ids = json.loads(r["source_message_ids"] or "[]")
            except json.JSONDecodeError:
                msg_ids = []
            prov_rows.append({
                "memory_id": mid,
                "conversation_id": r["conversation_id"],
                "message_ids": msg_ids,
            })
    files["provenance.jsonl"] = _jsonl_bytes(prov_rows)
    counts["provenance"] = len(prov_rows)

    # ---- README + manifest -----------------------------------------------
    files["README.md"] = _render_readme(SCHEMA_VERSION, timestamp).encode("utf-8")

    file_metadata: dict[str, dict[str, Any]] = {}
    for name, data in files.items():
        file_metadata[name] = {"sha256": _sha256_bytes(data), "size": len(data)}

    manifest = ExportManifest(
        schema_version=SCHEMA_VERSION,
        db_user_version=current_version(conn),
        timestamp=timestamp,
        user_id=user_id,
        redact_pii=redact_pii,
        counts=counts,
        files=file_metadata,
        bundle_path=str(out_path.resolve()),
    )
    manifest_bytes = json.dumps(
        manifest.to_dict(), indent=2, sort_keys=True, ensure_ascii=False
    ).encode("utf-8")

    # ---- assemble zip ----------------------------------------------------
    with zipfile.ZipFile(out_path, "w", compression=compression) as zf:
        # manifest first so streaming readers can validate before unpacking.
        zf.writestr("manifest.json", manifest_bytes)
        for name, data in files.items():
            zf.writestr(name, data)

    return manifest


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def verify_bundle(in_path: Path) -> dict[str, Any]:
    """Hash-check every payload file against the manifest. No DB writes.

    Returns ``{ok: bool, mismatches: [...], missing: [...], manifest: {...}}``.
    Never raises on a tampered bundle — instead reports the discrepancy so
    callers can decide whether to abort.
    """
    in_path = Path(in_path)
    if not zipfile.is_zipfile(in_path):
        return {"ok": False, "error": "not a zip", "manifest": None,
                "mismatches": [], "missing": []}
    with zipfile.ZipFile(in_path, "r") as zf:
        try:
            manifest = json.loads(zf.read("manifest.json").decode("utf-8"))
        except KeyError:
            return {"ok": False, "error": "manifest.json missing",
                    "manifest": None, "mismatches": [], "missing": []}
        files_meta = manifest.get("files", {})
        names = set(zf.namelist())
        mismatches: list[str] = []
        missing: list[str] = []
        for name, meta in files_meta.items():
            if name not in names:
                missing.append(name)
                continue
            data = zf.read(name)
            if _sha256_bytes(data) != meta.get("sha256"):
                mismatches.append(name)
            if int(meta.get("size", -1)) >= 0 and len(data) != meta["size"]:
                mismatches.append(name + " (size)")

    ok = not mismatches and not missing
    return {
        "ok": ok,
        "mismatches": sorted(set(mismatches)),
        "missing": sorted(set(missing)),
        "manifest": manifest,
    }


# ---------------------------------------------------------------------------
# Import
# ---------------------------------------------------------------------------


def _load_jsonl(zf: zipfile.ZipFile, name: str) -> list[dict[str, Any]]:
    try:
        raw = zf.read(name)
    except KeyError:
        return []
    rows: list[dict[str, Any]] = []
    for line in raw.decode("utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


def _insert_row(
    conn: sqlite3.Connection,
    table: str,
    row: dict[str, Any],
    *,
    skip_columns: set[str] | None = None,
) -> bool:
    """Insert ``row`` into ``table`` using only columns that exist on the
    target schema. Returns True if the row was inserted (False on integrity
    error / duplicate).
    """
    skip = skip_columns or set()
    available = set(_column_names(conn, table))
    cols = [c for c in row.keys() if c in available and c not in skip]
    if not cols:
        return False
    placeholders = ", ".join(["?"] * len(cols))
    cols_csv = ", ".join(cols)
    sql = f"INSERT OR IGNORE INTO {table} ({cols_csv}) VALUES ({placeholders})"
    try:
        cur = conn.execute(sql, [row.get(c) for c in cols])
    except sqlite3.IntegrityError:
        return False
    return cur.rowcount > 0


def _delete_user_rows(conn: sqlite3.Connection, user_id: str | None) -> dict[str, int]:
    """Delete every row attributable to ``user_id`` from the live DB.

    With the current default schema (no ``user_id`` column), 'replace' wipes
    every row in the affected tables; that's the only safe interpretation
    when the DB cannot tell rows apart by user.
    """
    deleted: dict[str, int] = {}
    cur = conn.cursor()
    if user_id and _has_column(conn, "memories", "user_id"):
        for table, sql in (
            ("memory_embeddings",
             "DELETE FROM memory_embeddings WHERE memory_id IN "
             "(SELECT id FROM memories WHERE user_id = ?)"),
            ("memory_entities",
             "DELETE FROM memory_entities WHERE memory_id IN "
             "(SELECT id FROM memories WHERE user_id = ?)"),
            ("memory_links",
             "DELETE FROM memory_links WHERE source_memory_id IN "
             "(SELECT id FROM memories WHERE user_id = ?) "
             "OR target_memory_id IN (SELECT id FROM memories WHERE user_id = ?)"),
            ("memories", "DELETE FROM memories WHERE user_id = ?"),
        ):
            if not _has_table(conn, table):
                continue
            params = (user_id, user_id) if "OR target_memory_id" in sql else (user_id,)
            cur.execute(sql, params)
            deleted[table] = cur.rowcount
        return deleted
    # No user column → wipe wholesale.
    for table in (
        "memory_links", "memory_entities", "memory_embeddings",
        "summary_node_members", "summary_nodes",
        "relationships", "entities",
        "memories",
        "messages", "conversations", "sources",
    ):
        if not _has_table(conn, table):
            continue
        cur.execute(f"DELETE FROM {table}")
        deleted[table] = cur.rowcount
    return deleted


def import_user_data(
    db: MemoirsDB,
    *,
    in_path: Path,
    mode: ImportMode = "merge",
    new_user_id: Optional[str] = None,
    verify: bool = True,
) -> ImportReport:
    """Re-hydrate a memoirs DB from a bundle previously emitted by
    :func:`export_user_data`.

    Modes
    -----
    - ``merge``     — ``INSERT OR IGNORE`` every row, preserving existing
                       data. Duplicates are silently skipped.
    - ``replace``   — first delete all rows attributable to the bundle's
                       ``user_id`` (or wipe everything when no user column),
                       then insert.
    - ``new_user``  — assign every imported memory to ``new_user_id`` (only
                       meaningful when the schema has a ``user_id`` column).
                       Original ids are preserved; FKs are remapped where the
                       bundle relies on them.
    """
    in_path = Path(in_path)
    if mode not in ("merge", "replace", "new_user"):
        raise ValueError(f"unknown import mode: {mode!r}")
    if mode == "new_user" and not new_user_id:
        raise ValueError("mode='new_user' requires new_user_id")

    if verify:
        verdict = verify_bundle(in_path)
        if not verdict["ok"]:
            raise ValueError(
                f"bundle verification failed: "
                f"missing={verdict['missing']} mismatches={verdict['mismatches']}"
            )

    conn = db.conn
    has_user_col = _has_column(conn, "memories", "user_id")

    with zipfile.ZipFile(in_path, "r") as zf:
        manifest = json.loads(zf.read("manifest.json").decode("utf-8"))
        report = ImportReport(
            schema_version=int(manifest.get("schema_version", 0)),
            db_user_version=int(manifest.get("db_user_version", 0)),
            mode=mode,
            user_id_target=new_user_id if mode == "new_user" else manifest.get("user_id"),
        )

        # ---- replace: pre-delete --------------------------------------
        if mode == "replace":
            report.deleted = _delete_user_rows(conn, manifest.get("user_id"))

        # ---- sources ---------------------------------------------------
        # Sources have an INTEGER PRIMARY KEY AUTOINCREMENT; we map the
        # original source id to whatever id the destination assigns. The
        # uri column is UNIQUE so we use it as the natural key.
        src_id_remap: dict[int, int] = {}
        sources_in = _load_jsonl(zf, "sources.jsonl")
        skipped_src = 0
        inserted_src = 0
        for s in sources_in:
            existing = conn.execute(
                "SELECT id FROM sources WHERE uri = ?", (s["uri"],)
            ).fetchone()
            if existing:
                src_id_remap[int(s["id"])] = int(existing[0])
                skipped_src += 1
                continue
            cols = [c for c in s.keys() if c in set(_column_names(conn, "sources")) and c != "id"]
            placeholders = ", ".join(["?"] * len(cols))
            cur = conn.execute(
                f"INSERT INTO sources ({', '.join(cols)}) VALUES ({placeholders})",
                [s.get(c) for c in cols],
            )
            new_id = int(cur.lastrowid)
            src_id_remap[int(s["id"])] = new_id
            inserted_src += 1
        report.inserted["sources"] = inserted_src
        report.skipped["sources"] = skipped_src

        # ---- conversations + messages ---------------------------------
        # Walk every conversations/<id>.jsonl entry. The first line is the
        # conversation header, the rest are messages.
        conv_inserted = msg_inserted = conv_skipped = msg_skipped = 0
        for name in zf.namelist():
            if not name.startswith("conversations/") or not name.endswith(".jsonl"):
                continue
            entries = _load_jsonl(zf, name)
            header: dict[str, Any] | None = None
            messages: list[dict[str, Any]] = []
            for e in entries:
                if e.get("__type__") == "conversation":
                    header = e
                elif e.get("__type__") == "message":
                    messages.append(e)
            if header is None:
                continue
            # Remap source_id via src_id_remap
            orig_sid = header.get("source_id")
            if orig_sid is not None and int(orig_sid) in src_id_remap:
                header["source_id"] = src_id_remap[int(orig_sid)]
            cleaned = {k: v for k, v in header.items() if k != "__type__"}
            if _insert_row(conn, "conversations", cleaned):
                conv_inserted += 1
            else:
                conv_skipped += 1
            for m in messages:
                cleaned = {k: v for k, v in m.items() if k != "__type__"}
                if _insert_row(conn, "messages", cleaned):
                    msg_inserted += 1
                else:
                    msg_skipped += 1
        report.inserted["conversations"] = conv_inserted
        report.inserted["messages"] = msg_inserted
        report.skipped["conversations"] = conv_skipped
        report.skipped["messages"] = msg_skipped

        # ---- memories --------------------------------------------------
        memories = _load_jsonl(zf, "memories.jsonl")
        m_inserted = m_skipped = 0
        for m in memories:
            if mode == "new_user" and has_user_col:
                m = {**m, "user_id": new_user_id}
            if _insert_row(conn, "memories", m):
                m_inserted += 1
            else:
                m_skipped += 1
        report.inserted["memories"] = m_inserted
        report.skipped["memories"] = m_skipped

        # ---- entities + memory_entities + relationships --------------
        for table in ("entities", "memory_entities", "relationships"):
            rows = _load_jsonl(zf, f"{table}.jsonl")
            inserted = skipped = 0
            for r in rows:
                if _insert_row(conn, table, r):
                    inserted += 1
                else:
                    skipped += 1
            report.inserted[table] = inserted
            report.skipped[table] = skipped

        # ---- memory_links + summary tree ----------------------------
        for table in ("memory_links", "summary_nodes", "summary_node_members"):
            if not _has_table(conn, table):
                continue
            rows = _load_jsonl(zf, f"{table}.jsonl")
            inserted = skipped = 0
            for r in rows:
                if _insert_row(conn, table, r):
                    inserted += 1
                else:
                    skipped += 1
            report.inserted[table] = inserted
            report.skipped[table] = skipped

        # ---- embeddings ------------------------------------------------
        try:
            blob = zf.read("embeddings.npz")
        except KeyError:
            blob = b""
        emb_inserted = emb_skipped = 0
        if blob:
            try:
                emb_rows = _npz_to_embeddings(blob)
            except Exception as exc:
                report.warnings.append(f"embeddings.npz unreadable: {exc}")
                emb_rows = []
            for r in emb_rows:
                cols = ["memory_id", "dim", "embedding", "model", "created_at"]
                try:
                    cur = conn.execute(
                        "INSERT OR IGNORE INTO memory_embeddings "
                        "(memory_id, dim, embedding, model, created_at) "
                        "VALUES (?, ?, ?, ?, ?)",
                        (r["memory_id"], r["dim"], r["embedding"], r["model"], r["created_at"]),
                    )
                    if cur.rowcount > 0:
                        emb_inserted += 1
                    else:
                        emb_skipped += 1
                except sqlite3.IntegrityError:
                    emb_skipped += 1
        report.inserted["embeddings"] = emb_inserted
        report.skipped["embeddings"] = emb_skipped

        conn.commit()

    return report


__all__ = [
    "ExportManifest",
    "ImportReport",
    "ImportMode",
    "SCHEMA_VERSION",
    "anonymize_memory",
    "export_user_data",
    "import_user_data",
    "verify_bundle",
]
